# Generated by Django 4.1.5 on 2023-02-01 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gbapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='associatedGuests',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True), max_length=500),
        ),
    ]
