# Generated by Django 4.1.5 on 2023-02-01 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gbapi', '0002_alter_guestdata_associatedguests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='associatedGuests',
            field=models.CharField(default=models.UUIDField(default=uuid.UUID('f6902da4-ba8d-41ba-9300-b1fb7abf8b0a'), editable=False, primary_key=True, serialize=False, unique=True), max_length=500),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='guestID',
            field=models.UUIDField(default=uuid.UUID('f6902da4-ba8d-41ba-9300-b1fb7abf8b0a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
