# Generated by Django 4.1.5 on 2023-02-01 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gbapi', '0003_alter_guestdata_associatedguests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='associatedGuests',
            field=models.CharField(default='Enter This Guest ID and Associated Guests Separated by COMMA (,)', max_length=500),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='guestID',
            field=models.UUIDField(default=uuid.UUID('6bccdf54-2b91-4f16-bd38-de15ea1fbd3e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
