# Generated by Django 4.1.5 on 2023-02-02 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gbapi', '0005_alter_guestdata_guestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='associatedGuests',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guestdata',
            name='guestID',
            field=models.UUIDField(default=uuid.UUID('8be15435-f313-436a-b6e0-22a8eb0b252e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
